# Config file for an example SF64: Recompiled mod.

# Fields that end up in the mod's manifest.
[manifest]

# Unique ID of this mod. Pick something long enough that it'll never be the same as any other mod.
# The name displayed in the mod management menu is separate from this so this doesn't need to be human readable.
id = "sf64_recomp_mod_playaskattship"

# Version of this mod.
version = "1.0.0"

# The name that will show up for this mod in the mod menu. This should be human readable.
display_name = "Use Katt's ship"

# The description that will show up when this mod is displayed in the mod menu. This should be human readable.
description =  """
Replaces the player's Arwing with Katts ship.

For more details, see https://github.com/sonicdcer/Sf64RecompMod_PlayAsKatt."""

# A short description that will show up in this mod's entry in the mod list. This should be human readable and kept short
# to prevent it from being cut off due to the limited space.
short_description = "Mod example that lets you have infinite bombs and twin laser."

# Authors of this mod.
authors = [ "SonicDcer" ]

# ID of the target recomp game.
game_id = "sf64"

# Minimum version of the target recomp (e.g. Starfox 64: Recompiled) that this mod can run on.
minimum_recomp_version = "1.0.0"

# Dependency mods. Each entry is the mod's ID and then an optional minimum version of the dependency mod.
dependencies = [
# Example dependency:
#    "modname:1.0.0"
]

# Native libraries (e.g. DLLs) and the functions they export.
native_libraries = [
# Example native library:
#    { name = "my_native_library", funcs = ["my_native_library_function"] }
]

# Inputs to the mod tool.
[inputs]

# Input elf file to generate a mod from.
elf_path = "build/mod.elf"

# Output mod filename.
mod_filename = "sf64_recomp_mod_PlayAsKattShip"

# Reference symbol files.
func_reference_syms_file = "Starfox64RecompSyms/sf64.us.rev1.syms.toml"
data_reference_syms_files = [ "Starfox64RecompSyms/sf64.us.rev1.datasyms.toml" ]

# Additional files to include in the mod.
additional_files = [ ]

[[manifest.config_options]]
id = "enum_option"
name = "Enum Option"
description = "Test enum config option"
type = "Enum"
options = [ "First", "Second" ]
default = "First"

[[manifest.config_options]]
id = "number_option"
name = "Number Option"
description = "Test number config option."
type = "Number"
min = 0
max = 10
step = 0.1
precision = 1
percent = false
default = 1

[[manifest.config_options]]
id = "string_option"
name = "String Option"
description = "Test string config option."
type = "String"
default = "Lorem Ipsum"
